version: '3.8'

services:
  api-gateway:
    build:
      context: ../api-gateway
    image: api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
    env_file:
      - ../api-gateway/.env  # Loads environment variables specific to api-gateway
    volumes:
      - ../api-gateway:/app  # Mounts the local directory to /app in the container

  auth-service:
    build:
      context: ../auth-service
    image: auth-service:latest
    ports:
      - "4000:4000"
    env_file:
      - ../auth-service/.env  # Loads environment variables specific to auth-service
    volumes:
      - ../auth-service:/app  # Mounts the local directory to /app in the container

  user-service:
    build:
      context: ../user-service
    image: user-service:latest
    ports:
      - "5000:5000"
    env_file:
      - ../user-service/.env  # Loads environment variables specific to user-service
    volumes:
      - ../user-service:/app  # Mounts the local directory to /app in the container
