version: '3.8'

services:
  api-gateway:
    build:
      context: ../api-gateway
    image: api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
    env_file:
      - ../api-gateway/.env
    volumes:
      - ../api-gateway:/app
    networks:
      - app-network

  auth-service:
    build:
      context: ../auth-service
    image: auth-service:latest
    ports:
      - "4000:4000"
    env_file:
      - ../auth-service/.env
    volumes:
      - ../auth-service:/app
    networks:
      - app-network

  user-service:
    build:
      context: ../user-service
    image: user-service:latest
    ports:
      - "5000:5000"
    env_file:
      - ../user-service/.env
    volumes:
      - ../user-service:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
