name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Compose services
        run: |
          docker-compose -f docker-compose.yaml build
          docker-compose push

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Set up Kubernetes context
#         run: |
#           kubectl config use-context minikube

#       - name: Deploy to Minikube
#         run: |
#           kubectl apply -f deployment.yaml
#           kubectl apply -f service.yaml
