name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3  # Updated to v3 for Node.js 20 compatibility

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to v3 for Node.js 20 compatibility
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest -f ./api-gateway/Dockerfile ./api-gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest -f ./auth-service/Dockerfile ./auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest -f ./user-service/Dockerfile ./user-service

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest


#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Set up Kubernetes context
#         run: |
#           kubectl config use-context minikube

#       - name: Deploy to Minikube
#         run: |
#           kubectl apply -f deployment.yaml
#           kubectl apply -f service.yaml
