name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest .
            docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .
            docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
  
        # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Set up Kubernetes context
#         run: |
#           kubectl config use-context minikube

#       - name: Deploy to Minikube
#         run: |
#           kubectl apply -f deployment.yaml
#           kubectl apply -f service.yaml
